# -*- coding: utf-8 -*-
"""UTCProcessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16g--y4vzvti1ixX3pc9qnBRfY-gYe8kv
"""

import pandas as pd
import numpy as np

xls = pd.ExcelFile('/content/Data for Datathon (Revised).xlsx')
df_interval1 = pd.read_excel(xls, 'A - Interval')
df_interval2 = pd.read_excel(xls, 'B - Interval')
df_interval3 = pd.read_excel(xls, 'C - Interval')
df_interval4 = pd.read_excel(xls, 'D - Interval')
df_daily1 = pd.read_excel(xls, 'A - Daily')
df_daily2 = pd.read_excel(xls, 'B - Daily')
df_daily3 = pd.read_excel(xls, 'C - Daily')
df_daily4 = pd.read_excel(xls, 'D - Daily')
orig_df1 = df_interval1
org_1 = df_interval1.shape
org_2 = df_interval2.shape
org_3 = df_interval3.shape
org_4 = df_interval4.shape

# df_interval1 = df_interval1.drop_duplicates(subset=['Interval'], keep='first')
# df_interval2 = df_interval2.drop_duplicates(subset=['Interval'], keep='first')
# df_interval3 = df_interval3.drop_duplicates(subset=['Interval'], keep='first')
# df_interval4 = df_interval4.drop_duplicates(subset=['Interval'], keep='first')


# rem_1 = df_interval1.shape
# rem_2 = df_interval2.shape
# rem_3 = df_interval3.shape
# rem_4 = df_interval4.shape

# check1 = (rem_1==org_1)
# check2 = (rem_2==org_2)
# check3 = (rem_3==org_3)
# check4 = (rem_4==org_4)

# org_1,rem_1
# iterable_xls = [df_interval1, df_interval2, df_interval3, df_interval4]
# for df_interval in iterable_xls:
#   for name in ['A - Interval', 'B - Interval', 'C - Interval', 'D - Interval']:
#     # print(f"\n=== {name} ===")
#     # print(df_interval['Interval'])
#     # df_interval['Interval'] = pd.to_datetime(df_interval['Interval'].astype(str))
#     # new_range = pd.date_range(df_interval['Interval'].values[0], df_interval['Interval'].values[-1], freq='30min')
#     # print(new_range.size)
#     df



df_interval1

df_interval1['Month'] = df_interval1['Month'].astype(str)
df_interval1['Day'] = df_interval1['Day'].astype(int)
month_to_num = {
    'January': 1, 'February': 2, 'March': 3, 'April': 4, 'May': 5, 'June': 6,
    'July': 7, 'August': 8, 'September': 9, 'October': 10, 'November': 11, 'December': 12
}

df_interval1['Month'] = df_interval1['Month'].map(month_to_num)

df_interval1

df_interval1['Date'] = '2025-' + df_interval1['Month'].astype(str) + '-' + df_interval1['Day'].astype(str).astype(str)

df_interval1

df_interval1['Date'] = df_interval1['Date'].apply(pd.to_datetime, format='%Y-%m-%d')

df_interval1

df_interval1['Date'] = pd.to_datetime(df_interval1['Date'])

df_interval1['Interval_TD'] = pd.to_timedelta(df_interval1['Interval'].astype(str))


df_interval1['Full_Timestamp'] = df_interval1['Date'] + df_interval1['Interval_TD']

df_interval1.head()

df_interval1['Full_Timestamp']=df_interval1['Full_Timestamp'].dt.tz_localize('UTC')

df_interval1 = df_interval1.drop(columns=['Date', 'Interval_TD'])
df_interval1.head()

duplicates = df_interval1[df_interval1.duplicated(subset=['Full_Timestamp'], keep='first')]
duplicates

start_ts = df_interval1['Full_Timestamp'].min()
end_ts = df_interval1['Full_Timestamp'].max()

full_range = pd.date_range(start=start_ts, end=end_ts, freq='30min', tz='UTC')
master_df = pd.DataFrame({'Full_Timestamp': full_range})

df_interval1 = pd.merge(master_df, df_interval1, on='Full_Timestamp', how='left')


df_interval1['Interval'] = df_interval1['Full_Timestamp'].dt.strftime('%H:%M:%S')
df_interval1['Month'] = df_interval1['Full_Timestamp'].dt.month
df_interval1['Day'] = df_interval1['Full_Timestamp'].dt.day

df_interval1

for i in range(1, 30, 1):
  specific_row_count = len(df_interval1[(df_interval1['Day'] == i )])
  print(specific_row_count)

daily_verification = df_interval1.groupby(df_interval1['Full_Timestamp'].dt.date).size()
incomplete_days = daily_verification[daily_verification != 48]

if incomplete_days.empty:
    print("Verification Successful: Every day has exactly 48 intervals (24 hours).")
else:
    print("Incomplete Data Found: The following dates do not have 48 intervals:")
    print(incomplete_days)

print("\nPreview of daily counts:")
print(daily_verification.head())

def process_interval_data(df, year=2025):


    df['Month'] = df['Month'].astype(str)
    df['Day'] = df['Day'].astype(int)

    month_to_num = {
        'January': 1, 'February': 2, 'March': 3, 'April': 4, 'May': 5, 'June': 6,
        'July': 7, 'August': 8, 'September': 9, 'October': 10, 'November': 11, 'December': 12
    }
    if df['Month'].iloc[0] in month_to_num:
        df['Month'] = df['Month'].map(month_to_num)


    df['Date'] = pd.to_datetime(f"{year}-" + df['Month'].astype(str) + '-' + df['Day'].astype(str))
    df['Interval_TD'] = pd.to_timedelta(df['Interval'].astype(str))
    df['Full_Timestamp'] = df['Date'] + df['Interval_TD']
    df['Full_Timestamp'] = df['Full_Timestamp'].dt.tz_localize('UTC')
    df = df.drop(columns=['Date', 'Interval_TD'])

    start_ts = df['Full_Timestamp'].min()
    end_ts = df['Full_Timestamp'].max()
    full_range = pd.date_range(start=start_ts, end=end_ts, freq='30min', tz='UTC')

    master_df = pd.DataFrame({'Full_Timestamp': full_range})
    df_cleaned = pd.merge(master_df, df, on='Full_Timestamp', how='left')


    df_cleaned['Interval'] = df_cleaned['Full_Timestamp'].dt.strftime('%H:%M:%S')
    df_cleaned['Month'] = df_cleaned['Full_Timestamp'].dt.month
    df_cleaned['Day'] = df_cleaned['Full_Timestamp'].dt.day

    return df_cleaned

df_interval2 = process_interval_data(df_interval2)

df_interval3 = process_interval_data(df_interval3)

df_interval4 = process_interval_data(df_interval4)

daily_verification = df_interval4.groupby(df_interval4['Full_Timestamp'].dt.date).size()
incomplete_days = daily_verification[daily_verification != 48]

if incomplete_days.empty:
    print("Verification Successful: Every day has exactly 48 intervals (24 hours).")
else:
    print("Incomplete Data Found: The following dates do not have 48 intervals:")
    print(incomplete_days)

print("\nPreview of daily counts:")
print(daily_verification.head())

df_daily1['Date'] = pd.to_datetime(df_daily1['Date'], format='%m/%d/%y %a')

def process_datetime_daily(df):
  df['Date'] = pd.to_datetime(df['Date'], format='%m/%d/%y %a')
  month_to_num = {
        'January': 1, 'February': 2, 'March': 3, 'April': 4, 'May': 5, 'June': 6,
        'July': 7, 'August': 8, 'September': 9, 'October': 10, 'November': 11, 'December': 12
    }
  if df['Month'].iloc[0] in month_to_num:
      df['Month'] = df['Month'].map(month_to_num)

  return df

df_daily1 = process_datetime_daily(df_daily2)
df_daily2 = process_datetime_daily(df_daily2)
df_daily3 = process_datetime_daily(df_daily3)
df_daily4 = process_datetime_daily(df_daily4)